apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: rollout-demo2-destrule
spec:
  host: rollout-demo2
  subsets:
  - name: canary-demo2   # referenced in canary.trafficRouting.istio.destinationRule.canarySubsetName
    labels:        # labels will be injected with canary rollouts-pod-template-hash value
      app: rollout-demo2
  - name: stable-demo2   # referenced in canary.trafficRouting.istio.destinationRule.stableSubsetName
    labels:        # labels will be injected with stable rollouts-pod-template-hash value
      app: rollout-demo2
